bash run.sh net/coderextreme/data/KoreanCharacterMotionAnnexB01Jin.java
bash run.sh net/coderextreme/data/ball.java
bash run.sh net/coderextreme/data/JinEyesClosed.java
bash run.sh net/coderextreme/data/fors.java
bash run.sh net/coderextreme/data/force_tidy.java
bash run.sh net/coderextreme/data/JinInnerBrowRaiser.java
bash run.sh net/coderextreme/data/Lily5Final.java
bash run.sh net/coderextreme/data/browser.java
bash run.sh net/coderextreme/data/Humanoid4NoSegSite.java
bash run.sh net/coderextreme/data/LOA1_StopAnimation.java
bash run.sh net/coderextreme/data/HAnimPoseExternProtoDeclare.java
bash run.sh net/coderextreme/data/JoeDemo5JoeSkin5_Final.java
bash run.sh net/coderextreme/data/JoeKickAnimation.java
bash run.sh net/coderextreme/data/rubikOnFire.java
bash run.sh net/coderextreme/data/JointCoordinateAxes.java
bash run.sh net/coderextreme/data/Bushes.java
bash run.sh net/coderextreme/data/SquawLOD023.java
bash run.sh net/coderextreme/data/CleanedWink.java
bash run.sh net/coderextreme/data/ballcge.java
bash run.sh net/coderextreme/data/bobblespheres.java
bash run.sh net/coderextreme/data/KoreanCharacter05Ju.java
bash run.sh net/coderextreme/data/JinLipSuck.java
bash run.sh net/coderextreme/data/JinScaledV2L1LOA4Sites08e.java
bash run.sh net/coderextreme/data/plainflowers.java
bash run.sh net/coderextreme/data/HAnimModelFootRight.java
bash run.sh net/coderextreme/data/New2Template.java
bash run.sh net/coderextreme/data/LOA1_WalkAnimation.java
bash run.sh net/coderextreme/data/flowers4.java
bash run.sh net/coderextreme/data/Humanoid3.java
bash run.sh net/coderextreme/data/JinWink.java
bash run.sh net/coderextreme/data/HAnimModelHandLeft.java
bash run.sh net/coderextreme/data/mobiusDon.java
bash run.sh net/coderextreme/data/Leif8Final.java
bash run.sh net/coderextreme/data/bubs3.java
bash run.sh net/coderextreme/data/JoeSkeletonSkinSiteSaluteWalk.java
bash run.sh net/coderextreme/data/Leif5Final.java
bash run.sh net/coderextreme/data/Connectors.java
bash run.sh net/coderextreme/data/text3shapes.java
bash run.sh net/coderextreme/data/KoreanCharacter03Hyun.java
bash run.sh net/coderextreme/data/rubik.java
bash run.sh net/coderextreme/data/StandardHumanoidNoSegSite.java
bash run.sh net/coderextreme/data/HAnimPosePrototype.java
bash run.sh net/coderextreme/data/cgeparticleflowers.java
bash run.sh net/coderextreme/data/gridBack.java
bash run.sh net/coderextreme/data/FacialAnimationComparisonScripts.java
bash run.sh net/coderextreme/data/JinLOA4_scaled1_Final.java
bash run.sh net/coderextreme/data/asmallbox.java
bash run.sh net/coderextreme/data/ifscubeworks.java
bash run.sh net/coderextreme/data/app.java
bash run.sh net/coderextreme/data/JoeHAnimKick1a_Final.java
bash run.sh net/coderextreme/data/JoeSkeletonSkinSite.java
bash run.sh net/coderextreme/data/freewrlflowers.java
bash run.sh net/coderextreme/data/Teapot.java
bash run.sh net/coderextreme/data/AllenDutton.java
bash run.sh net/coderextreme/data/Humanoid3NoSegSite.java
bash run.sh net/coderextreme/data/JinLipTightener.java
bash run.sh net/coderextreme/data/StringArrayEncodingExamples.java
bash run.sh net/coderextreme/data/Lily8Final.java
bash run.sh net/coderextreme/data/KoreanCharacter02Chul.java
bash run.sh net/coderextreme/data/abox.java
bash run.sh net/coderextreme/data/KoreanCharacter11Min.java
bash run.sh net/coderextreme/data/Humanoid0.java
bash run.sh net/coderextreme/data/Jin20fSegmented.java
bash run.sh net/coderextreme/data/flowers2.java
bash run.sh net/coderextreme/data/JinLidDroop.java
bash run.sh net/coderextreme/data/ifscube.java
bash run.sh net/coderextreme/data/Humanoid4_1.java
bash run.sh net/coderextreme/data/MyBounce.java
bash run.sh net/coderextreme/data/mobiusCarlson.java
bash run.sh net/coderextreme/data/SplitChannels.java
bash run.sh net/coderextreme/data/JinLOA4_3.java
bash run.sh net/coderextreme/data/Tufani8Final.java
bash run.sh net/coderextreme/data/indexedfacesetPixeltexture_plus.java
bash run.sh net/coderextreme/data/JinLOA1RigidBody.java
bash run.sh net/coderextreme/data/KoreanCharacterMotionAnnexD01Jin.java
bash run.sh net/coderextreme/data/JoeSkinTexcoordDisplacerKick.java
bash run.sh net/coderextreme/data/LOA1_SwimmingFlutterKickAnimation.java
bash run.sh net/coderextreme/data/ArtDecoPrototypes.java
bash run.sh net/coderextreme/data/JinLipStretcher.java
bash run.sh net/coderextreme/data/indexedfacesetPixeltexture_part.java
bash run.sh net/coderextreme/data/ArchHalf.java
bash run.sh net/coderextreme/data/arc1.java
bash run.sh net/coderextreme/data/IcosahedronSubdivisionLevel5.java
bash run.sh net/coderextreme/data/Humanoid2.java
bash run.sh net/coderextreme/data/Nodes.java
bash run.sh net/coderextreme/data/KoreanCharacter08Da.java
bash run.sh net/coderextreme/data/JinDimpler.java
bash run.sh net/coderextreme/data/JoeSkinTexcoordDisplacerKickUpdate2.java
bash run.sh net/coderextreme/data/asphere.java
bash run.sh net/coderextreme/data/MultiTextureDesignPattern.java
bash run.sh net/coderextreme/data/bubble.java
bash run.sh net/coderextreme/data/JinLOA1.java
bash run.sh net/coderextreme/data/Trebuchet.java
bash run.sh net/coderextreme/data/SmokeTestProgramOutput.java
bash run.sh net/coderextreme/data/geobubbles.java
bash run.sh net/coderextreme/data/mobius.java
bash run.sh net/coderextreme/data/JinUpperLidRaiser.java
bash run.sh net/coderextreme/data/HelloWorldCommented.java
bash run.sh net/coderextreme/data/JinMouthStretch.java
bash run.sh net/coderextreme/data/Humanoid2NoSegSite.java
bash run.sh net/coderextreme/data/arc.java
bash run.sh net/coderextreme/data/arc4.java
bash run.sh net/coderextreme/data/HelloWorldMinimal.java
bash run.sh net/coderextreme/data/JinLipsPart.java
bash run.sh net/coderextreme/data/bumpyfreewrl.java
bash run.sh net/coderextreme/data/fwparticleflowers.java
bash run.sh net/coderextreme/data/ViewFrustumExample.java
bash run.sh net/coderextreme/data/OrientationInterpolator.java
bash run.sh net/coderextreme/data/BackToCoordinate.java
bash run.sh net/coderextreme/data/JinNoseWrinkler.java
bash run.sh net/coderextreme/data/bumpyx_ite.java
bash run.sh net/coderextreme/data/CADPartChildNoTransformation.java
bash run.sh net/coderextreme/data/rubikPly.java
bash run.sh net/coderextreme/data/CanonicalFacialAnimationComparisonScripts.java
bash run.sh net/coderextreme/data/TextExamples.java
bash run.sh net/coderextreme/data/LOA1_KneelAnimation.java
bash run.sh net/coderextreme/data/JinCheekPuffer.java
bash run.sh net/coderextreme/data/ObliqueStrategies.java
bash run.sh net/coderextreme/data/JinJawDrop.java
bash run.sh net/coderextreme/data/InlineSoundSource.java
bash run.sh net/coderextreme/data/ballx_ite.java
bash run.sh net/coderextreme/data/forcenode.java
bash run.sh net/coderextreme/data/variationalflowers2.java
bash run.sh net/coderextreme/data/JohnJoint2.java
bash run.sh net/coderextreme/data/JinChinRaiser.java
bash run.sh net/coderextreme/data/CleanedYouClocks.java
bash run.sh net/coderextreme/data/CameraShape.java
bash run.sh net/coderextreme/data/indexedfacesetPixeltexture_whole.java
bash run.sh net/coderextreme/data/JinLOA4scaled1joe06c.java
bash run.sh net/coderextreme/data/JinUpperLipRaiser.java
bash run.sh net/coderextreme/data/JinConcat11c.java
bash run.sh net/coderextreme/data/CameraPrototypes.java
bash run.sh net/coderextreme/data/Filters.java
bash run.sh net/coderextreme/data/MaskAndSnorkel.java
bash run.sh net/coderextreme/data/x3dconnector.java
bash run.sh net/coderextreme/data/KoreanCharacter07No.java
bash run.sh net/coderextreme/data/HelloWorld.java
bash run.sh net/coderextreme/data/Oxytocin.java
bash run.sh net/coderextreme/data/JoeExample.java
bash run.sh net/coderextreme/data/rgb_alpha.java
bash run.sh net/coderextreme/data/x3dconnectorProto.java
bash run.sh net/coderextreme/data/JinLOA4_6.java
bash run.sh net/coderextreme/data/flower.java
bash run.sh net/coderextreme/data/ArchPrototype.java
bash run.sh net/coderextreme/data/bumpyx_itesliders.java
bash run.sh net/coderextreme/data/LOA1_JumpAnimation.java
bash run.sh net/coderextreme/data/IFS.java
bash run.sh net/coderextreme/data/CatByMuru.java
bash run.sh net/coderextreme/data/BoxEm.java
bash run.sh net/coderextreme/data/JinLOA4_5.java
bash run.sh net/coderextreme/data/geo.java
bash run.sh net/coderextreme/data/jumpcut_loadurl.java
bash run.sh net/coderextreme/data/qq3.java
bash run.sh net/coderextreme/data/ArtDecoExamples.java
bash run.sh net/coderextreme/data/variationalflowers.java
bash run.sh net/coderextreme/data/AllenBox.java
bash run.sh net/coderextreme/data/New2TemplateNoBoxes.java
bash run.sh net/coderextreme/data/ExtrusionHeart.java
bash run.sh net/coderextreme/data/sphereflowers.java
bash run.sh net/coderextreme/data/KoreanCharacter12Sun.java
bash run.sh net/coderextreme/data/CaliforniaCampuses.java
bash run.sh net/coderextreme/data/LOA1_RunAnimation.java
bash run.sh net/coderextreme/data/JinLipPressor.java
bash run.sh net/coderextreme/data/Bubbles.java
bash run.sh net/coderextreme/data/HAnimBehaviorPrototypes.java
bash run.sh net/coderextreme/data/KoreanCharacter10Mi.java
bash run.sh net/coderextreme/data/DesignPatternsApparelMedicalSkinLayers.java
bash run.sh net/coderextreme/data/JinLipFunneler.java
bash run.sh net/coderextreme/data/ballx3dom.java
bash run.sh net/coderextreme/data/CoordinateAxes.java
bash run.sh net/coderextreme/data/KoreanCharacter01Jin.java
bash run.sh net/coderextreme/data/JinScaledV2L1LOA4Sites10h.java
bash run.sh net/coderextreme/data/ThreeDTexture.java
bash run.sh net/coderextreme/data/flower3.java
bash run.sh net/coderextreme/data/ManyClocks.java
bash run.sh net/coderextreme/data/JinLowerLipDepressor.java
bash run.sh net/coderextreme/data/JinBrowLowerer.java
bash run.sh net/coderextreme/data/arc3.java
bash run.sh net/coderextreme/data/JinBlink.java
bash run.sh net/coderextreme/data/Humanoid1.java
bash run.sh net/coderextreme/data/bubs.java
bash run.sh net/coderextreme/data/CleanedMultiFacialAnimationMenu.java
bash run.sh net/coderextreme/data/bumpyfreewrljsonverse.java
bash run.sh net/coderextreme/data/flowerprotofreewrl.java
bash run.sh net/coderextreme/data/JoeKick.java
bash run.sh net/coderextreme/data/sliders.java
bash run.sh net/coderextreme/data/rubikFurnace.java
bash run.sh net/coderextreme/data/arc2.java
bash run.sh net/coderextreme/data/HalloweenPumpkinLanternKnight.java
bash run.sh net/coderextreme/data/flowers.java
bash run.sh net/coderextreme/data/JoeDemo5JoeSkin5a.java
bash run.sh net/coderextreme/data/arcold.java
bash run.sh net/coderextreme/data/ThreeInARow.java
bash run.sh net/coderextreme/data/bub.java
bash run.sh net/coderextreme/data/HAnimModelHandRight.java
bash run.sh net/coderextreme/data/flipp.java
bash run.sh net/coderextreme/data/DonHumanoid.java
bash run.sh net/coderextreme/data/DonHumanoidNoSegSite.java
bash run.sh net/coderextreme/data/JinSquint.java
bash run.sh net/coderextreme/data/particleballs.java
bash run.sh net/coderextreme/data/SingleMenuJin.java
bash run.sh net/coderextreme/data/JinSlit.java
bash run.sh net/coderextreme/data/myextrusion.java
bash run.sh net/coderextreme/data/JohnJoint20.java
bash run.sh net/coderextreme/data/SheenCloth.java
bash run.sh net/coderextreme/data/JinScaledV2L1LOA4OnlyMarkers11g.java
bash run.sh net/coderextreme/data/KoreanCharacter06Ga.java
bash run.sh net/coderextreme/data/SimpleShader.java
bash run.sh net/coderextreme/data/RouteJin.java
bash run.sh net/coderextreme/data/RotationTests.java
bash run.sh net/coderextreme/data/indexedfacesetPixeltexture_entire.java
bash run.sh net/coderextreme/data/JinLipCornerPuller.java
bash run.sh net/coderextreme/data/MultiFacialAnimationMenu.java
bash run.sh net/coderextreme/data/GridXZ_20x20Fixed.java
bash run.sh net/coderextreme/data/KoreanCharacterMotionAnnexC01Jin.java
bash run.sh net/coderextreme/data/particleflowers.java
bash run.sh net/coderextreme/data/JinLOA4_1.java
bash run.sh net/coderextreme/data/JinCheekRaiser.java
bash run.sh net/coderextreme/data/LOA1_StandAnimation.java
bash run.sh net/coderextreme/data/ScubaTank.java
bash run.sh net/coderextreme/data/x3domflowers.java
bash run.sh net/coderextreme/data/JinLipPuckerer.java
bash run.sh net/coderextreme/data/SpatialAudioCameraAnimation.java
bash run.sh net/coderextreme/data/KoreanCharacter09Ru.java
bash run.sh net/coderextreme/data/fors2.java
bash run.sh net/coderextreme/data/JinLipCornerDepressor.java
bash run.sh net/coderextreme/data/HAnimPoseExample.java
bash run.sh net/coderextreme/data/blenderSkeleton.java
bash run.sh net/coderextreme/data/bumpyfreewrlsliders.java
bash run.sh net/coderextreme/data/YehudiMenuJin.java
bash run.sh net/coderextreme/data/JinOuterBrowRaiser.java
bash run.sh net/coderextreme/data/JinNasolabialDeepener.java
bash run.sh net/coderextreme/data/glflowers.java
bash run.sh net/coderextreme/data/force.java
bash run.sh net/coderextreme/data/flowerproto.java
bash run.sh net/coderextreme/data/StandardHumanoid.java
bash run.sh net/coderextreme/data/bubs2.java
bash run.sh net/coderextreme/data/pp3.java
bash run.sh net/coderextreme/data/Humanoid4.java
bash run.sh net/coderextreme/data/BoxEm2.java
bash run.sh net/coderextreme/data/JinLOA4.java
bash run.sh net/coderextreme/data/asteroids.java
bash run.sh net/coderextreme/data/gears.java
bash run.sh net/coderextreme/data/mirror.java
bash run.sh net/coderextreme/data/Marine.java
bash run.sh net/coderextreme/data/Pathway.java
bash run.sh net/coderextreme/data/Size2tExample_revision2.java
bash run.sh net/coderextreme/data/JinScaledV2L1LOA4Sites07f.java
bash run.sh net/coderextreme/data/Tufani5Final.java
bash run.sh net/coderextreme/data/MainStage.java
bash run.sh net/coderextreme/data/JinLOA4_4.java
bash run.sh net/coderextreme/data/Menu.java
bash run.sh net/coderextreme/data/Humanoid1NoSegSite.java
bash run.sh net/coderextreme/data/HAnimModelFootLeft.java
bash run.sh net/coderextreme/data/mirror2.java
bash run.sh net/coderextreme/data/Cane.java
bash run.sh net/coderextreme/data/ViewFrustumPrototype.java
bash run.sh net/coderextreme/data/Tongue.java
bash run.sh net/coderextreme/data/personal.java
bash run.sh net/coderextreme/data/flowers7.java
bash run.sh net/coderextreme/data/KoreanCharacter04Young.java
bash run.sh net/coderextreme/data/JohnJoint.java
bash run.sh net/coderextreme/data/JinLidTightener.java
bash run.sh net/coderextreme/data/MenuJin.java
