bash run.sh net/coderextreme/data/ArtDecoExamples.java
bash run.sh net/coderextreme/data/CaliforniaCampuses.java
bash run.sh net/coderextreme/data/CoordinateAxes.java
bash run.sh net/coderextreme/data/HAnimPoseExample.java
bash run.sh net/coderextreme/data/HAnimPoseExternProtoDeclare.java
bash run.sh net/coderextreme/data/InlineSoundSource.java
bash run.sh net/coderextreme/data/JoeDemo5JoeSkin5a.java
bash run.sh net/coderextreme/data/JoeDemo5JoeSkin5_Final.java
bash run.sh net/coderextreme/data/JoeHAnimKick1a_Final.java
bash run.sh net/coderextreme/data/JoeSkeletonSkinSite.java
bash run.sh net/coderextreme/data/JoeSkeletonSkinSiteSaluteWalk.java
bash run.sh net/coderextreme/data/Leif5Final.java
bash run.sh net/coderextreme/data/Leif8Final.java
bash run.sh net/coderextreme/data/Lily5Final.java
bash run.sh net/coderextreme/data/Lily8Final.java
bash run.sh net/coderextreme/data/MainStage.java
bash run.sh net/coderextreme/data/New2Template.java
bash run.sh net/coderextreme/data/New2TemplateNoBoxes.java
bash run.sh net/coderextreme/data/personal.java
bash run.sh net/coderextreme/data/Tufani5Final.java
bash run.sh net/coderextreme/data/Tufani8Final.java
bash run.sh net/coderextreme/data/ViewFrustumExample.java
