bash run.sh net/coderextreme/data/rubikOnFire.java
bash run.sh net/coderextreme/data/KoreanCharacter01Jin.java
bash run.sh net/coderextreme/data/JoeKickAnimation.java
bash run.sh net/coderextreme/data/HalloweenPumpkinLanternKnight.java
bash run.sh net/coderextreme/data/JinWink.java
bash run.sh net/coderextreme/data/BoxEm.java
bash run.sh net/coderextreme/data/ArchHalf.java
bash run.sh net/coderextreme/data/Humanoid4.java
bash run.sh net/coderextreme/data/rubikFurnace.java
bash run.sh net/coderextreme/data/rubik.java
bash run.sh net/coderextreme/data/rubikPly.java
exit
bash run.sh net/coderextreme/data/Leif5Final.java
bash run.sh net/coderextreme/data/Leif8Final.java
bash run.sh net/coderextreme/data/Lily5Final.java
bash run.sh net/coderextreme/data/Lily8Final.java
bash run.sh net/coderextreme/data/Tufani5Final.java
bash run.sh net/coderextreme/data/Tufani8Final.java
exit
bash run.sh net/coderextreme/data/HalloweenPumpkinLanternKnight.java
bash run.sh net/coderextreme/data/HAnimBehaviorPrototypes.java
bash run.sh net/coderextreme/data/HAnimModelFootLeft.java
bash run.sh net/coderextreme/data/HAnimModelFootRight.java
bash run.sh net/coderextreme/data/HAnimModelHandLeft.java
bash run.sh net/coderextreme/data/HAnimModelHandRight.java
bash run.sh net/coderextreme/data/HAnimPoseExample.java
bash run.sh net/coderextreme/data/HAnimPoseExternProtoDeclare.java
bash run.sh net/coderextreme/data/HAnimPosePrototype.java
bash run.sh net/coderextreme/data/HelloWorldCommented.java
bash run.sh net/coderextreme/data/HelloWorld.java
bash run.sh net/coderextreme/data/HelloWorldMinimal.java
bash run.sh net/coderextreme/data/Humanoid0.java
bash run.sh net/coderextreme/data/Humanoid1.java
bash run.sh net/coderextreme/data/Humanoid1NoSegSite.java
bash run.sh net/coderextreme/data/Humanoid2.java
bash run.sh net/coderextreme/data/Humanoid2NoSegSite.java
bash run.sh net/coderextreme/data/Humanoid3.java
bash run.sh net/coderextreme/data/Humanoid3NoSegSite.java
bash run.sh net/coderextreme/data/Humanoid4_1.java
bash run.sh net/coderextreme/data/Humanoid4.java
bash run.sh net/coderextreme/data/Humanoid4NoSegSite.java
bash run.sh net/coderextreme/data/Jin20fSegmented.java
bash run.sh net/coderextreme/data/JinBlink.java
bash run.sh net/coderextreme/data/JinBrowLowerer.java
bash run.sh net/coderextreme/data/JinCheekPuffer.java
bash run.sh net/coderextreme/data/JinCheekRaiser.java
bash run.sh net/coderextreme/data/JinChinRaiser.java
bash run.sh net/coderextreme/data/JinConcat11c.java
bash run.sh net/coderextreme/data/JinDimpler.java
bash run.sh net/coderextreme/data/JinEyesClosed.java
bash run.sh net/coderextreme/data/JinInnerBrowRaiser.java
bash run.sh net/coderextreme/data/JinJawDrop.java
bash run.sh net/coderextreme/data/JinLidDroop.java
bash run.sh net/coderextreme/data/JinLidTightener.java
bash run.sh net/coderextreme/data/JinLipCornerDepressor.java
bash run.sh net/coderextreme/data/JinLipCornerPuller.java
bash run.sh net/coderextreme/data/JinLipFunneler.java
bash run.sh net/coderextreme/data/JinLipPressor.java
bash run.sh net/coderextreme/data/JinLipPuckerer.java
bash run.sh net/coderextreme/data/JinLipsPart.java
bash run.sh net/coderextreme/data/JinLipStretcher.java
bash run.sh net/coderextreme/data/JinLipSuck.java
bash run.sh net/coderextreme/data/JinLipTightener.java
bash run.sh net/coderextreme/data/JinLOA1.java
bash run.sh net/coderextreme/data/JinLOA1RigidBody.java
bash run.sh net/coderextreme/data/JinLOA4_1.java
bash run.sh net/coderextreme/data/JinLOA4_3.java
bash run.sh net/coderextreme/data/JinLOA4_4.java
bash run.sh net/coderextreme/data/JinLOA4_5.java
bash run.sh net/coderextreme/data/JinLOA4_6.java
bash run.sh net/coderextreme/data/JinLOA4.java
bash run.sh net/coderextreme/data/JinLOA4_scaled1_Final.java
bash run.sh net/coderextreme/data/JinLOA4scaled1joe06c.java
bash run.sh net/coderextreme/data/JinLowerLipDepressor.java
bash run.sh net/coderextreme/data/JinMouthStretch.java
bash run.sh net/coderextreme/data/JinNasolabialDeepener.java
bash run.sh net/coderextreme/data/JinNoseWrinkler.java
bash run.sh net/coderextreme/data/JinOuterBrowRaiser.java
bash run.sh net/coderextreme/data/JinScaledV2L1LOA4OnlyMarkers11g.java
bash run.sh net/coderextreme/data/JinScaledV2L1LOA4Sites07f.java
bash run.sh net/coderextreme/data/JinScaledV2L1LOA4Sites08e.java
bash run.sh net/coderextreme/data/JinScaledV2L1LOA4Sites10h.java
bash run.sh net/coderextreme/data/JinSlit.java
bash run.sh net/coderextreme/data/JinSquint.java
bash run.sh net/coderextreme/data/JinUpperLidRaiser.java
bash run.sh net/coderextreme/data/JinUpperLipRaiser.java
bash run.sh net/coderextreme/data/JinWink.java
bash run.sh net/coderextreme/data/JoeDemo5JoeSkin5a.java
bash run.sh net/coderextreme/data/JoeDemo5JoeSkin5_Final.java
bash run.sh net/coderextreme/data/JoeExample.java
bash run.sh net/coderextreme/data/JoeHAnimKick1a_Final.java
bash run.sh net/coderextreme/data/JoeKickAnimation.java
bash run.sh net/coderextreme/data/JoeKick.java
bash run.sh net/coderextreme/data/JoeSkeletonSkinSite.java
bash run.sh net/coderextreme/data/JoeSkeletonSkinSiteSaluteWalk.java
bash run.sh net/coderextreme/data/JoeSkinTexcoordDisplacerKick.java
bash run.sh net/coderextreme/data/JoeSkinTexcoordDisplacerKickUpdate2.java
bash run.sh net/coderextreme/data/KoreanCharacter01Jin.java
bash run.sh net/coderextreme/data/KoreanCharacter02Chul.java
bash run.sh net/coderextreme/data/KoreanCharacter03Hyun.java
bash run.sh net/coderextreme/data/KoreanCharacter04Young.java
bash run.sh net/coderextreme/data/KoreanCharacter05Ju.java
bash run.sh net/coderextreme/data/KoreanCharacter06Ga.java
bash run.sh net/coderextreme/data/KoreanCharacter07No.java
bash run.sh net/coderextreme/data/KoreanCharacter08Da.java
bash run.sh net/coderextreme/data/KoreanCharacter09Ru.java
bash run.sh net/coderextreme/data/KoreanCharacter10Mi.java
bash run.sh net/coderextreme/data/KoreanCharacter11Min.java
bash run.sh net/coderextreme/data/KoreanCharacter12Sun.java
bash run.sh net/coderextreme/data/KoreanCharacterMotionAnnexB01Jin.java
bash run.sh net/coderextreme/data/KoreanCharacterMotionAnnexC01Jin.java
bash run.sh net/coderextreme/data/KoreanCharacterMotionAnnexD01Jin.java
